### ISSUE TITLE
Supporting mutiple main files (entry points) for a single project

### ISSUE THREAD

**Issue by n-pn** [crystal-lang-tools/vscode-crystal-lang#175]
Currently the extension only support a single entry point with the `Main File` option. But with a large project with many files and multiple entry points (for example microservice webapps) it it not a ideal situation.

For example I have a project with this structure:
```
/src
├── service_1
│   ├── service_1_foo.cr
│   ├── service_1_bar.cr
│   ├── ... a dozen more
├── service_1.cr # includes all file in service_1 folder
├── service_2
│   ├── service_2_foo.cr
│   ├── service_2_bar.cr
│   ├── ... a dozen more
├── service_2.cr # includes all file in service_2 folder
├── service_3.cr # ...
├── program_4.cr # ...
└── utilities # the other services require some file here
```
The services might have conflicting dependencies, so creating another file and require all the file (and point the Main File to it) is not possible as it can cause both compilation time error and runtime error.

So in order to make the extension to work properly I need to change the Main File setting every time I switch from working with service_a to service_b, or just give up making it work again.

Also, as Crystal/Crystalline struggle with larger projects, ideally we need to keep the files required count as little as possible. For example in the example folder structure, the working file `service_1_foo.cr` at most will only need the files from `service_1` folder, the files from `utilities` folder and the files from `lib`. The files from `service_2` and other services should not be included in the checking. 

Another scenario is you implement the code in file `src/service_x/foo.cr` and write the test in `spec/service_x/foo_test.cr`. Ideally the main file of current working file `src/service_x/foo.cr` is `spec/service_x/foo_test.cr`, not `src/service_x.cr` so it can be even faster to check the error.

So I hope the extension can support multiple entry points (Main File) mapping for a single project. The structure can be like this:

```yml
endpoints:
  - main: spec/service_1/foo_spec.cr
    include: [src/service_1/foo.cr]
    
  - main: src/service_1.cr
    include: [src/service_1/**/*.cr, src/utilities/**/*.cr]
    exclude: [src/utilities/blacklist_this_file_so_it_can_fallback_to_other_endpoint.cr]
  
  - main: src/service_2.cr
 
  - main: spec/spec_helper.cr # capture-all endpoint as fallback
    include: [src/**/*]
```

For the current working file it will run through the include/exclude filters and return the first endpoint that matches. You can switch the main file of the current file by moving the rule up or down.

Also, since the file content can change a lot, it might be better to save it as .vscode setting instead of putting it in `shard.yml`
